### ISSUE TITLE
Use email instead of username - passport

### ISSUE THREAD

**Issue by leopucci** [kevoj/nodetomic-api-swagger#10]
Hi!
Thanks for your boilerplate. I learned a lot on it. 

Could you help me out with something? 
Username is not so useful these days although passport is based on username, i was wondering if there is some easy way to migrate all the system from username based to e-mail based

Thanks!

**Comment by bytesleo** [comment]
Hi, thanks to you for exploring the repository, of course, look at this file:
https://github.com/kevoj/nodetomic-api-swagger/blob/master/src/api/models/statics/user.static.js
* Replace all "username" to "email"

https://github.com/kevoj/nodetomic-api-swagger/blob/master/src/api/models/user.model.js
* clone line 6 to 21

**Comment by bytesleo** [comment]
Soon I will release version 4, with incredible improvements, and very lite, less code and more power!

**Comment by leopucci** [comment]
Thanks for your help!
