### ISSUE TITLE
Bellisimo!  Redis-JWT question

### ISSUE THREAD

**Issue by rjpalermo1** [kevoj/nodetomic-api-swagger#3]
Had to stop in and thank you for the best stack I've seen so far - - - and I've downloaded and jacked with most of them.

I'm making it mine now, setting up configs and such figuring out Express and Node.  This is the first time I've seen Passport, I'll dig in but I notice you have a callback commented out in the local.js.  I think I need to focus there...what I want to do is add a user param in the JWT, after the JWT is verified I want to take this param and query the User to retrieve a value and based on the value take action.  Is this a good starting point?

**Comment by bytesleo** [comment]
hello @rjpalermo1, thank you very much for using nodetomic-api-swagger I am glad too !. As for your question you can focus on the following file: https://github.com/kevoj/nodetomic-api-swagger/blob/develop/src/auth/services/session.js in this file all passport come after to log in correctly, and on line 21 you can store data in redis example: dataSession: {example: 123}, but if you want to save data in the token you can simply put: dataToken: {example: 123} For more information you can consult my repository from redis-jwt https://github.com/kevoj/redis-jwt

**Comment by bytesleo** [comment]
@rjpalermo1 then in the file https://github.com/kevoj/nodetomic-api-swagger/blob/develop/src/auth/services/mw.js on line 16 if you want to bring the stored data simply add a true leaving of the following way: r.verify (token, true);
/*
{
 "rjwt": "507f191e810c19729de860ea:ZYYlwOGqTmx",
 "dataToken": [Object]
 "dataSession": [Object]
 "iat": 1504334208,
 "id": "507f191e810c19729de860ea",
 "ttl": 60
}
*/

**Comment by rjpalermo1** [comment]
Thank you kevoj!  

I'm on it!

Hey, by the way take a look at a framework that just came out - well actually 2 of them pretty new I've been scoping out.  I am intending on learning and using your awesome stack as my base and eventually try to get the capabilities these provide to play nice.

API Gateway called express-gateway: https://github.com/ExpressGateway/express-gateway

A plug-in framework built on Express called DataFire:  https://github.com/DataFire/DataFire

... hoping you see some more sugar here for your stack actually ;)
