### ISSUE TITLE
Add new path

### ISSUE THREAD

**Issue by rjpalermo1** [kevoj/nodetomic-api-swagger#4]
Hey kevoj,

I'm really sorry to bother you but I'm having a hell of a time trying to set up a simple path.  I where I think I need to be in path.js and tried a dozen different variants trying to get a simple console.log to print.  

``` 
  // ADD PATHS HERE!

  app.get('/:uri(ladies)', (req, res) => {
    console.log('hello ladies');
  });

  app.use('/:uri(ladies)', (req, res) => {
    console.log('hello ladies');
  });
```

I know you have some magic going on here.  Possible to add a few blurbs in your README showing how to...

1.  Add a page from a path
2.  Call a remote service from a path like `https://httpbin/ip` ?

**Comment by bytesleo** [comment]
Do not worry, I'll explain to you in a simple way.

The folder you should use to do what you are is https://github.com/kevoj/nodetomic-api-swagger/tree/develop/src/api

Look at the example at https://github.com/kevoj/nodetomic-api-swagger/blob/develop/src/api/swagger/hello.yaml

for your case simply create the **ladies.yaml** file inside **/api/swagger/**

```yaml
/api/ladies:
   x-swagger-router-controller: ladies
   get
     operationId: nameMethod
     description: Returns ladies
     responses:
       200:
         description: Success
```
then create the **ladies.js** file inside **/api/controller/**

```javascript
import {result} from 'express-easy-helper';

export function nameMethod (req, res) {
   console.log('hello ladies');
   result(res, 'hello ladies'); // return response
}
```
and ready! that is all! you can already access the url http://localhost:8000/api/ladies

**Comment by rjpalermo1** [comment]
THANK YOU!

Yes it makes sense and I'm starting to get the feel for this.  You're a champ!

**Comment by bytesleo** [comment]
Thank you very much for your star to the repository my friend!
