### ISSUE TITLE
default.html not found

### ISSUE THREAD

**Issue by rjpalermo1** [kevoj/nodetomic-api-swagger#5]
Hi,

I think this last push you did broke something.  I did a clean install and now getting:

Error: ENOENT: no such file or directory, stat  '.../src/views/default/default.html'

;)

**Comment by bytesleo** [comment]
Hey u can do console.log to var "file" in /lib/express/client.js before comment "Folder client" and show me the value, ty!

**Comment by rjpalermo1** [comment]
Ok, wiped everything clean and starting a brand new build.  FYI, the swagger version is set to 6.22 and won't let me `yarn` (I'm latest node 8.5) if that matters at all.

**Comment by rjpalermo1** [comment]
```
  // Point static path to client by default
  let client = config.client;
  let file = 'index';

  // If not exits client, when set internal default
  if (!fs.existsSync(config.client)) {
    client = `${config.base}/views/default`;
    file = config.mode;
    if (config['socket.io'].example) {
      app.use('/socket', express.static(`${client}/socket.html`));
      app.use('/token', express.static(`${client}/token.html`));
    }
  }

  app.use(express.static(client));
  app.use(favicon(path.join(client, 'favicon.ico')));

  console.log('file = ', + file);
  console.debug('file = ', + file);
```
does not return any value - console in Chrome inspector =  `GET http://localhost:8000/ 404 (Not Found)`

terminal returns `GET / 404 6.290 ms - 249 Error: ENOENT: no such file or directory, stat '.../api-gateway/server/src/views/default/default.html`

UPDATE:  I also changed ports to some random port in case 8000 was blocked - same result.  Server starting fine, favicon loads...

**Comment by rjpalermo1** [comment]
UPDATE!!!!

So I decided to do the restart and the server started just fine.  I've been hammering on this all day experimenting with different env's and likely had a port blocked or necessary resource was not available.

Feel dumb - So sorry for bothering you - know you're busy.  I'll close this now...

**Comment by bytesleo** [comment]
Hahaha don't worry! I'm sorry I could not help you the moment you asked me since it was from the cell phone, I'm glad to know it was not a bug!  
Anything you do not worry about asking, right now you are the one who finds the bugs! :D

**Comment by bytesleo** [comment]
In a few days I will  the official release and update the documentation to make it friendlier!

**Comment by rjpalermo1** [comment]
Ok kevoj, if you don't mind me throwing in my 2 cents here and there where I get tangled up or where in my humble opinion I could use a little friendlier experience - I'd be happy to help however I can.

Let's start with an easy one.

How about having an option in the development config where we can turn on or off the seed data?  I like using nodemon but find that any user-related work I do gets destroyed every time I save a file.

> PS, I know I can just comment the seed methods in and out of the config/index.js each time...I'm just real anal about having a bunch of commented code - it gets confusing....

**Comment by bytesleo** [comment]
check in https://github.com/kevoj/nodetomic-api-swagger/blob/develop/src/config/index.js
 line 44 and 49  multiple options for seeds :D!

**Comment by rjpalermo1** [comment]
Ah-ha!  Yes that is perfect - you're way ahead of the game.  I read through that code and didn't put 2 + 2 together (plant -> seed).  So is `'alway` a shorthand programming term for `always`?

**Comment by bytesleo** [comment]
You're right it should be called "always"!
