### ISSUE TITLE
ReDoc Support (feature request)

### ISSUE THREAD

**Issue by rjpalermo1** [kevoj/nodetomic-api-swagger#6]
Hi kevoj,

Recommend taking a look at ReDoc ~ beautiful api docs for folks who aren't keen on Swagger but want to document their APIs without the "try it out" feature.

https://github.com/Rebilly/ReDoc/blob/master/README.md

It looks like an easy integration (but what do I know)...

**Comment by bytesleo** [comment]
I'll take a look, you have to know that I also have a repo without swagger: D  https://github.com/kevoj/nodetomic-api

**Comment by rjpalermo1** [comment]
You continue to surprise me...a wizard you are.

I happen to like swagger for development, makes things easy for testing and grabbing tokens/keys.  Haven't put anything into production but if I do someday don't think I want to make swagger available - just my personal taste but I think it is very ugly and don't want a bunch of random people banging on my server all day (if only I could get that lucky).  Curious to what you think after glancing at redoc - it actually fits your theme out of the box....

**Comment by bytesleo** [comment]
hahaha when you are in production and do not want to leave swagger enabled the public you only have to change the value in line 77 of this file: https://github.com/kevoj/nodetomic-api-swagger/blob/develop/src/config/production.js

**Comment by rjpalermo1** [comment]
yes - I'm at the pont where I am assuming you have these things covered...but then I don't have any documentation on the APIs if I remove Swagger.  No biggie, thought it would be a compelling addition to your stack, maybe I'll grow up someday and do things myself....

**Comment by bytesleo** [comment]
hey very soon I will finish the generator of generators, look at my repository, in this you can configure how you want the stack https://github.com/kevoj/generator-scaling-fullstack, this already includes working with Angular, Vue, React or if you want swagger or if you just want express routers, and more....

Note: In the release I promise to put better documentation on the whole stack!

**Comment by rjpalermo1** [comment]
I AM ON IT!!!!

Is it ready for testing?  Want me to report back?

**Comment by bytesleo** [comment]
I warn you friend when you are ready for testing, right now you are in a beta with Reactjs, if you want to try it and tell me!

**Comment by rjpalermo1** [comment]
Of course - exciting stuff.  I'll report glitches as I come across them to help you.  Is this the best place to do it or want me to report on your repo?

So here is FYI building with latest node 8.5

npm WARN deprecated babel-preset-es2016@6.24.1: We're really excited that you're trying to use ES2016 syntax, but instead of making more yearly presets, Babel has a better preset that we recommend you use instead: npm install babel-preset-env --save-dev. Give us a follow @babeljs to get more updates

**Comment by rjpalermo1** [comment]
You can set up a Project https://github.com/kevoj/generator-scaling-fullstack/projects and I can add small things there that are under development if you want so your Issues list to start incrementing.  This could be a good test case and great experience for me to help - I consider myself on the left-uphill side of the bell curve on programming skills but climbing fast....

**Comment by bytesleo** [comment]
WARN deprecated babel-preset-es2016@6.24.1 where did that come from? 

https://github.com/kevoj/generator-scaling-fullstack/projects would be fine, very soon I will return to this repository to program it in form, I warn you when you can start, for the moment I will conserve this repository  https://github.com/kevoj/generator-scaling-fullstack as a great experiment that will fit all the stacks

**Comment by rjpalermo1** [comment]
> this repository https://github.com/kevoj/generator-scaling-fullstack as a great experiment that will fit all the stacks

I agree with you.  

The warn came on 'npm rebuild'  I yo'd in a terminal that had node 7.78 then opened `code .` which was terminal was running node 8.5.  I  got a bcrypt error on `npm start` due to the original yo building on 7.78 and me trying to run it with 8.5 - it advised me to do the `npm rebuild` and that is where I got the babel-preset warning.

**Comment by kevoj** [comment]
Great, out of curiosity where are you from?

**Comment by rjpalermo1** [comment]
American - I live in Dominican Republic for last 3 years, you?
