### ISSUE TITLE
Yarn install fails

### ISSUE THREAD

**Issue by rjpalermo1** [kevoj/nodetomic-api-swagger#8]
On a fresh build and using `yarn` instead of `npm -1` receiving the following error:

```
[1/5] 🔍  Validating package.json...
error nodetomic-api-swagger@3.3.8: The engine "node" is incompatible with this module. Expected version "^6.2.2".
error Found incompatible module
```

Likely related to:  https://github.com/yarnpkg/yarn/issues/1160

adding the `--ignore-engines` flag fixes this.  `yarn --ignore-engines`

**Comment by bytesleo** [comment]
It has been documented in the installation, thank you!
